apiVersion: v1
kind: ConfigMap
metadata:
  name: python-app-config
data:
  APP_ENV: "prod"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: myrepo/python-app:v1
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: python-app-config
